// Generated by Wrangler by running `wrangler --experimental-json-config types` (hash: 62eb8263b35b62aa157d037f1c43a80c)
// Runtime types generated with workerd@1.20250321.0 2024-11-01 nodejs_compat
declare namespace Cloudflare {
    interface Env {
        iyuu_token: string;
        ftqq_token: string;
        api_key: string;
        Crypto: Fetcher;
        ASSETS: Fetcher;
    }
}
interface Env extends Cloudflare.Env {}